- hosts: all
  # become: true
  gather_facts: false
  tasks:
  
  - name: install nginx
    ansible.builtin.apt:
      name: nginx
      state: latest
    tags: nginx
    become: yes

  - name: copy HTML
    ansible.builtin.copy:
      src: index.html
      dest: /usr/share/nginx/html/index.html
    become: yes

  - name: update nginx config
    ansible.builtin.copy:
      src: nginx.conf
      dest: /etc/nginx/nginx.conf
    notify:
      - restart nginx
    become: yes

  - name: nginx systemd
    ansible.builtin.systemd:
      name: nginx
      enabled: yes
      state: started
    become: yes

  handlers:
  - name: restart nginx
    ansible.builtin.systemd:
      name: nginx
      state: reloaded
    become: yes