- hosts: all
  gather_facts: false
  tasks:
    - name: create user
      ansible.builtin.user:
        name: ansible-worker
        state: present
      become_user: root

    - name: install git
      ansible.builtin.apt:
        name: git
        state: latest
      become_user: ansible-worker
      tags: git

    - name: check dir exsist
      ansible.builtin.file:
        path: /home/ansible-worker/www/
        state: directory

    - name: load SSH-pub
      authorized_key:
        user: ansible-worker
        key: "{{ lookup('file', 'ssh_keys/id_rsa.pub') }}"

    - name: clone repo
      ansible.builtin.git:
        repo: 'https://git@github.com/iphilka/stud-template.git'
        dest: /home/ansible-worker/www/
        accept_hostkey: yes
        key_file: ~/www/stud-template/ssh_keys/id_rsa

    - name: install nginx
      ansible.builtin.apt:
        name: nginx
        state: latest
      become_user: ansible-worker
      notify:
      - link with sites-enabled

    - name: update nginx config
      ansible.builtin.copy:
        src: nginx.conf
        dest: /etc/nginx/nginx.conf
      notify:
      - restart nginx
      become: yes
      
    - name: update nginx config
      ansible.builtin.copy:
        src: ansible.iphilka.ru.conf
        dest: /etc/nginx/sites-available
      become_user: ansible-worker
      notify:
      - nginx start

    - name: copy HTML
      ansible.builtin.copy:
        src: index.html
        dest: /usr/share/nginx/html/index.html
      become: yes

  handlers:
    - name: link with sites-enabled
      ansible.builtin.shell:
        cmd: sudo ln -s /etc/nginx/sites-available/ansible.iphilka.ru.conf /etc/nginx/sites-enabled
      become: yes

    - name: nginx start
      ansible.builtin.systemd:
        name: nginx
        enabled: yes
        state: started
      become: yes

    - name: restart nginx
      ansible.builtin.systemd:
        name: nginx
        state: reloaded
      become: yes
